//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PotatoCornerSys
{
    public partial class ProfileAdmin
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.LinkButton lnkSales;
        protected global::System.Web.UI.WebControls.LinkButton lnkUpdate;
        protected global::System.Web.UI.WebControls.LinkButton lnkProfile;
        protected global::System.Web.UI.WebControls.Label lblUsername;
        protected global::System.Web.UI.WebControls.Label lblFullname;
        protected global::System.Web.UI.WebControls.Label lblEmail;
        protected global::System.Web.UI.WebControls.Label lblPhone;
        protected global::System.Web.UI.WebControls.Label lblAddress;
        protected global::System.Web.UI.WebControls.Label lblRole;
        protected global::System.Web.UI.WebControls.Label lblTotalUsers;
        protected global::System.Web.UI.WebControls.Label lblTotalOrders;
        protected global::System.Web.UI.WebControls.Label lblPendingOrders;
        protected global::System.Web.UI.WebControls.Label lblTotalRevenue;
        protected global::System.Web.UI.WebControls.Button btnBackToDashboard;
        protected global::System.Web.UI.WebControls.Button btnDatabaseBackup;
        protected global::System.Web.UI.WebControls.Button btnLogout;
    }
}
