//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PotatoCornerSys
{
    public partial class Update
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.LinkButton lnkSales;
        protected global::System.Web.UI.WebControls.LinkButton lnkUpdate;
        protected global::System.Web.UI.WebControls.LinkButton lnkProfile;
        protected global::System.Web.UI.WebControls.Panel pnlLowStockAlert;
        protected global::System.Web.UI.WebControls.Label lblLowStockItems;
        protected global::System.Web.UI.WebControls.GridView gvStock;
    }
}
